const API = '/.netlify/functions/game';
const state = { playerId: localStorage.getItem('ff-player-id') || crypto.randomUUID(), room: null, code: '', lastPhase: '', timer: null, poll: null, hasAnswered: false };
localStorage.setItem('ff-player-id', state.playerId);
const $ = (id) => document.getElementById(id);
const show = (id) => document.querySelectorAll('.screen').forEach((s) => s.classList.toggle('active', s.id === id));
const toast = (msg) => { $('toast').textContent = msg; $('toast').classList.add('show'); setTimeout(() => $('toast').classList.remove('show'), 2400); };
async function request(method, payload={}) { const r = await fetch(API, { method, headers: method==='POST'?{'content-type':'application/json'}:undefined, body:method==='POST'?JSON.stringify(payload):undefined }); const data=await r.json(); if(!r.ok) throw new Error(data.error||'Something went wrong.'); return data; }
function nameFrom(id){ return state.room?.players.find(p=>p.id===id)?.name || 'Player'; }
async function create(){ const name=$('createName').value.trim(); if(!name)return toast('Enter your name first.'); try{ const room=await request('POST',{action:'create',name,playerId:state.playerId}); enterRoom(room); }catch(e){toast(e.message)} }
async function join(){ const name=$('joinName').value.trim(), code=$('joinCode').value.trim().toUpperCase(); if(!name||code.length!==5)return toast('Enter your name and 5-letter room code.'); try{ const room=await request('POST',{action:'join',name,code,playerId:state.playerId}); enterRoom(room); }catch(e){toast(e.message)} }
function enterRoom(room){ state.room=room; state.code=room.code; $('roomBadge').textContent=`ROOM ${room.code}`; $('roomBadge').classList.remove('hidden'); update(room); startPolling(); }
function startPolling(){
  clearTimeout(state.pollOnce);
  pollNow();
}
async function pollNow(){ try{ const room=await fetch(`${API}?action=state&code=${encodeURIComponent(state.code)}`).then(async r=>{const d=await r.json(); if(!r.ok)throw new Error(d.error); return d}); update(room); }catch(e){ if(!e.message.includes('Room not found')) console.warn(e); } finally { clearTimeout(state.pollOnce); state.pollOnce=setTimeout(pollNow,750); } }
function update(room){ state.room=room; if(room.phase==='lobby') renderLobby(room); if(room.phase==='question') renderQuestion(room); if(room.phase==='results') renderResults(room); if(room.phase==='finished') renderFinished(room); }
function renderLobby(room){ show('lobby'); $('lobbyCode').textContent=room.code; $('playerList').innerHTML=room.players.map(p=>`<div class="player"><span>${escapeHtml(p.name)}${p.id===room.hostId?' <small>HOST</small>':''}</span><strong>${p.score}</strong></div>`).join(''); const isHost=room.players.some(p=>p.id===state.playerId&&p.id===room.hostId); $('startBtn').classList.toggle('hidden',!isHost); $('hostHint').textContent=isHost?(room.players.length<2?'Invite at least one more player.':'Everyone is in. Start when ready.'):'Waiting for the host to start…'; }
function renderQuestion(room){ show('question'); const q=room.question; $('roundLabel').textContent=`ROUND ${room.round} / 3`; $('answeredLabel').textContent=`${room.answered.length} / ${room.players.length} answered`; $('categoryLabel').textContent=q.category; $('questionText').textContent=q.prompt; $('choices').innerHTML=q.choices.map((c,i)=>`<button class="choice" data-choice="${i}" ${state.hasAnswered||room.answered.includes(state.playerId)?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span>${escapeHtml(c)}</button>`).join(''); state.hasAnswered=room.answered.includes(state.playerId); $('answerStatus').textContent=state.hasAnswered?'Locked in. Waiting for the other drivers…':'Pick one answer. Speed matters after correctness.'; $('choices').querySelectorAll('.choice').forEach(b=>b.onclick=()=>answer(Number(b.dataset.choice))); $('scoreBar').innerHTML=room.players.slice().sort((a,b)=>b.score-a.score).map(p=>`<span class="mini-score">${escapeHtml(p.name)} · ${p.score}</span>`).join(''); runTimer(room.questionStartedAt); }
function runTimer(start){ clearInterval(state.timer); const tick=()=>{const left=Math.max(0,15-Math.floor((Date.now()-start)/1000)); $('timer').textContent=left; if(left===0) clearInterval(state.timer)}; tick(); state.timer=setInterval(tick,250); }
async function answer(choice){ if(state.hasAnswered)return; state.hasAnswered=true; document.querySelectorAll('.choice').forEach(b=>b.disabled=true); try{ const room=await request('POST',{action:'answer',code:state.code,playerId:state.playerId,choice}); update(room); }catch(e){state.hasAnswered=false; toast(e.message)} }
function renderResults(room){ show('results'); clearInterval(state.timer); const sorted=room.players.slice().sort((a,b)=>b.score-a.score); $('resultsList').innerHTML=sorted.map((p,i)=>`<div class="result"><span class="rank">#${i+1}</span><span>${escapeHtml(p.name)}</span><span class="points">${p.score} pts</span></div>`).join(''); const host=room.hostId===state.playerId; $('nextBtn').classList.toggle('hidden',!host); $('nextBtn').textContent=room.round>=3?'Show winner':'Next round'; state.hasAnswered=false; }
async function next(){ try{ const room=await request('POST',{action:'next',code:state.code,playerId:state.playerId}); update(room); }catch(e){toast(e.message)} }
function renderFinished(room){ show('finished'); clearInterval(state.timer); const sorted=room.players.slice().sort((a,b)=>b.score-a.score), winner=sorted[0]; $('winnerName').textContent=winner.name; $('winnerScore').textContent=`${winner.score} points after 3 rounds`; $('finalList').innerHTML=sorted.map((p,i)=>`<div class="result"><span class="rank">#${i+1}</span><span>${escapeHtml(p.name)}</span><span class="points">${p.score}</span></div>`).join(''); }
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
$('createBtn').onclick=create; $('joinBtn').onclick=join; $('startBtn').onclick=async()=>{try{update(await request('POST',{action:'start',code:state.code,playerId:state.playerId}))}catch(e){toast(e.message)}}; $('nextBtn').onclick=next; $('copyBtn').onclick=async()=>{await navigator.clipboard.writeText(state.code);toast('Room code copied.');}; $('joinCode').addEventListener('input',e=>e.target.value=e.target.value.replace(/[^a-zA-Z0-9]/g,'').toUpperCase().slice(0,5));
